#! /bin/sh

sxhkd &

# Colors:
bg_color='#202020'
sec_color='#fed7ae'
text_color='#f3f4f5'
inactive_text_color='#676e7d'
urgent_bg_color='#d78272'
def_font='Quicksand, Bold 11'


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap		5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color    $sec_color
bspc config active_border_color	    $bg_color
bspc config normal_border_color	    $bg_color

bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
bspc rule -a Gnome-calendar desktop='^4'
bspc rule -a Evolution desktop='^4'
bspc rule -a jetbrains-idea-ce desktop='^5'
bspc rule -a jetbrains-pycharm-ce desktop='^5'
bspc rule -a jetbrains-studio desktop='^5'
bspc rule -a "" desktop='^10'
bspc rule -a Lollypop desktop='^10'

# Autostart
restart_list="dunst compton kdeconnect-indicator /usr/lib/geoclue-2.0/demos/agent redshift-gtk clipit"
for p in $restart_list; do
    killall $p
    $p &
done

fix_xcursor
nm-applet
autorandr -c --force
nitrogen --restore
$HOME/.config/polybar/launch.sh

ps caux | grep spotify > /dev/null
if (( $? != 0 )); then
    spotify &
fi

sleep 0.1

exit 0

